import 'dart:math';

import 'package:flutter/material.dart';

class PasswordViewModel extends ChangeNotifier {
  List<String> names = [
    " robert-sanchez",
    " Thiago Silva",
    " Marc Cucurella ",
    " Ben Chilwell ",
    " Callum Hudson-Odoi",
    " Hakim Ziyech",
    " Christian Pulisic ",
    " Romelu Lukaku",
    " Raheem Sterling",
    " Enzo Fernández",
    " Mateo Kovačić",
    "Kai Havertz",
    " Edouard Mendy",
    " Azpilicueta",
    " Reece James",
    "Kalidou Koulibaly",
    " Mason Mount",
    " Pierre-Emerick Aubameyang",
    " João Félix",
    " Frank Lampard",
    " Marcos Alonso",
    " Antonio Rüdiger",
    " N'Golo Kanté",
    " Jorginho",
    " Saúl",
    " Timo Werner",
    " Thomas Tuchel",
    " Andreas Christensen",
    " Kurt Zouma",
    " Olivier Giroud",
    " Tammy Abraham",
    " Michy Batshuayi",
    " Fikayo Tomori",
    " Willian",
    " Eden Hazard",
    " Gonzalo Higuaín",
    " Maurizio Sarri",
    " David Luiz",
    " Álvaro Morata",
    " Pedro",
    " Antonio Conte",
    " Thibaut Courtois",
    " Nathan Aké",
    "John Terry",
    "Cesc Fàbregas",
    " Nemanja Matić",
    " Diego Costa",
    " Oscar",
    " Alexandre Pato",
    " Radamel Falcao",
    " Petr Čech",
    " Juan Cuadrado",
    " Didier Drogba",
    " josé Mourinho",
    " Samuel Eto'o",
    " Fernando Torres",
    " Mo Salah",
    " André Schürrle",
    " Ashley Cole",
    " Florent Malouda ",
    " Michael Essien",
    " Daniel Sturridge",
    " Michael Ballack",
    " Carlo Ancelotti",
    " Ricardo Carvalho",
    " Ricardo Quaresma",
    " Claude Makélélé",
    " Andriy Shevchenko",
    " Lassana Diarra",
    " Arjen Robben",
    " Dean Henderson",
    " André Onana",
    " Eric Bailly",
    " Diogo Dalot",
    " Victor Lindelöf",
    " Harry Maguire",
    " Tyrell Malacia",
    " Lisandro Martínez",
    " Luke Shaw",
    " Raphaël Varane",
    " Aaron Wan-Bissaka",
    " Bruno Fernandes",
    " Casemiro",
    " Scott McTominay",
    " Donny van de Beek",
    " Antony",
    " Alejandro Garnacho",
    " Rasmus Højlund",
    " Anthony Martial",
    " Marcus Rashford",
    " Jadon Sancho",
    " Erik ten Hag",
    " De Gea",
    " Fred",
    " Zidane Iqbal",
    " Marcel Sabitzer",
    " Anthony Elanga",
    " Wout Weghorst",
    " Alex Telles",
    " Jesse Lingard",
    " Mata",
    " Paul Pogba",
    " Édinson Cavani",
    " Cristiano Ronaldo",
    " Mason Greenwood",
    " Ole Gunnar Solskjær",
    " Michael Carrick",
    " Phil Jones",
    " Andreas Pereira",
    " Antonio Valencia",
    " Chris Smalling",
    " Marcos Rojo",
    " Ander Herrera",
    " Marouane Fellaini",
    " Matteo Darmian",
    " Zlatan Ibrahimović",
    " Wayne Rooney",
    " Víctor Valdés",
    " Daley Blind",
    " Bastian Schweinsteiger",
    " Memphis Depay",
    " Ryan Giggs",
    " Louis van Gaal",
    " Patrice Evra",
    " Nemanja Vidić",
    " Paul Scholes",
    " Ashley Young",
    " Javier Hernández",
    " Nani",
    " Alex Ferguson",
    " Ederson",
    " Stefan Ortega",
    " Rúben Dias",
    " Josko Gvardiol",
    " Nathan Aké",
    " John Stones",
    " Manuel Akanji",
    " Aymeric Laporte",
    " João Cancelo",
    " Rodri",
    " Kalvin phillips ",
    " Bernardo Silva",
    " Kevin De Bruyne",
    " Phil Foden",
    " Jack Grealish",
    " Erling halaand",
    " Julián Álvarez",
    " Benjamin Mendy",
    " Riyad Mahrez",
    " Ilkay Gündogan",
    " Ferran Torres",
    " Eric García",
    " Fernandinho",
    " Sergio Agüero",
    " Claudio Bravo",
    " Nicolás Otamendi",
    " David Silva",
    " Leroy Sané",
    " Danilo",
    " Vincent Kompany",
    " Eliaquim Mangala",
    " Fabian Delph",
    " Douglas Luiz",
    " Brahim Díaz",
    " Pep Guardiola",
    " Nolito",
    " Kelechi Iheanacho",
    " Jesús Navas",
    " Yaya Touré",
    " Pablo Zabaleta",
    " Wilfried Bony",
    " Manuel Pellegrini",
    " James Milner",
    " Edin Džeko",
    " Maicon",
    " Carlos Tévez",
    " Stefan Savić",
    " David Pizarro",
    " Jérôme Boateng",
    " Mario Balotelli",
    " Roberto Mancini",
    " Aaron Ramsdale",
    " William Saliba",
    " Gabriel Magalhães ",
    " Oleksandr Zinchenko",
    " Kieran Tierney",
    " Declan Rice",
    " Thomas Partey",
    " Mohamed Elneny",
    " Martin Ødegaard ",
    " Emile Smith Rowe",
    " Gabriel Martinelli",
    " Leandro Trossard",
    " Bukayo Saka",
    " Nicolas Pépé",
    " Gabriel Jesus",
    " Eddie Nketiah",
    " Granit Xhaka",
    " Bernd Leno",
    " Héctor Bellerín",
    " Alexandre Lacazette",
    " Cédric Soares",
    " Dani Ceballos",
    " Joe Willock",
    " Emiliano Martínez",
    " Henrikh Mkhitaryan",
    " Mesut Özil",
    " David Ospina",
    " Aaron Ramsey",
    " Denis Suárez",
    " Santi Cazorla",
    " Alexis Sánchez",
    " Wojciech Szczesny",
    " Mikel Arteta",
    " Serge Gnabry",
    " Alex Oxlade-Chamberlain",
    " Lukas Podolski",
    " Lukasz Fabianski",
    " Gervinho",
    " Samir Nasri",
    " Thierry Henry",
    " Kolo Touré",
    " Robin van Persie",
    " Emmanuel Adebayor",
    " Dennis Bergkamp",
    " Danny Welbeck",
    " Rio Ferdinand",
    " Ji-Sung Park",
    " Michael Owen",
    " Edwin van der Sar",
    " Cristiano Ronaldo",
    " Gary Neville",
    " Piqué",
    " Ruud van Nistelrooy",
    " Phil Neville",
    " Roy Keane",
    " Diego Forlán",
    " David Beckham",
    " Juan Sebastián Verón",
    " Eric Cantona",
    " Jaap Stam",
    " Alisson",
    " Trent Alexander-Arnold",
    " Joe Gomez",
    " Ibrahima Konaté",
    " Joel Matip",
    " Andy Robertson",
    " Virgil van Dijk",
    " Harvey Elliott",
    " Alexis Mac Allister",
    " Dominik Szoboszlai",
    " Thiago",
    " Luis Díaz",
    " Diogo Jota",
    " Cody Gakpo",
    " Darwin Núñez",
    " Jürgen Klopp",
    " Fabinho",
    " Jordan Henderson",
    " Naby Keïta",
    " Roberto Firmino",
    " Georginio Wijnaldum",
    " Sadio Mané",
    " Xherdan Shaqiri",
    " Adam Lallana",
    " Daniel Sturridge",
    " Loris Karius",
    " Emre Can",
    " Danny Ings",
    " Dominic Solanke",
    " Coutinho",
    " Lucas Leiva",
    " Divock Origi",
    " Steven Gerrard",
    " Luis Alberto",
    " Iago Aspas",
    " Luis Suárez",
    " Pepe Reina",
    " Maximiliano Rodríguez",
    " Javier Mascherano",
    " Xabi Alonso",
    " Peter Crouch",
    " Rafa Benítez",
    " Nick Pope",
    " Sven Botman",
    " Dan Burn",
    " Kieran Trippier",
    " Miguel Almirón",
    " Bruno Guimarães",
    " Joelinton",
    " Sandro Tonali",
    " Anthony Gordon",
    " Alexander Isak",
    " Alexander Isak",
    " Eddie Howe",
    " Allan Saint-Maximin",
    " Jason Steele",
    " Pervis Estupiñán",
    " Lewis Dunk",
    " Pascal Groß",
    " Solly March",
    " Kaoru Mitoma",
    " João Pedro",
    " Julio Enciso",
    " Roberto De Zerbi",
    " Ben Mee",
    " Rico Henry",
    " Bryan Mbeumo",
    " Ivan Toney",
    " Yoane Wissa",
    " Ollie Watkins",
    " Jordan Pickford",
    " Danny Ward",
    " Wilfred Ndidi",
    " Jamie Vardy",
    " Harvey Barnes",
    " James Maddison",
    " Kepa",
    " Andriy Lunin",
    " David Alaba",
    " Álvaro Odriozola",
    " Dani Carvajal",
    " Eder Militão",
    " Lucas Vázquez",
    " Ferland Mendy",
    " Nacho",
    " Antonio Rüdiger",
    " Jude Bellingham",
    " Eduardo Camavinga",
    " Arda Güler",
    " Toni Kroos",
    " Luka Modrić",
    " Aurélien Tchouaméni",
    " Federico Valverde",
    " Joselu",
    " Rodrygo",
    " Vinícius Junior",
    " Jesús Vallejo",
    " Marco Asensio",
    " Mariano",
    " Marcelo",
    " Isco",
    " Gareth Bale",
    " Karim Benzema",
    " Luka Jović",
    " Alphonse Aréola",
    " Sergio Ramos",
    " Zinédine Zidane",
    " Kiko Casilla",
    " Keylor Navas",
    " Achraf Hakimi",
    " Theo Hernández",
    " Marcos Llorente",
    " Borja Mayoral",
    " Arbeloa",
    " Pepe",
    " James Rodríguez",
    " Jesé",
    " Ángel Di María",
    " Sami Khedira",
    " Fábio Coentrão",
    " Raúl Albiol",
    " Kaká",
    " Nuri Şahin",
    " José Callejón",
    " Guti",
    " Rafael van der Vaart",
    " Raúl",
    " Iker Casillas",
    " Fabio Cannavaro",
    " Míchel Salgado",
    " Dani Parejo",
    " Wesley Sneijder",
    " Javier Saviola",
    " Robinho",
    " Roberto Carlos",
    " Luís Figo",
    " Ronaldo",
    " Hierro",
    " Morientes",
    " Clarence Seedorf",
    " Jan Oblak",
    " José Giménez",
    " Mario Hermoso",
    " Reinildo",
    " Çağlar Söyüncü",
    " Yannick Carrasco",
    " Rodrigo De Paul",
    " Koke",
    " Thomas Lemar",
    " Axel Witsel",
    " Ángel Correa",
    " Antoine Griezmann",
    " Diego Simeone",
    " Geoffrey Kondogbia",
    " Giuliano Simeone",
    " Matheus Cunha",
    " Renan Lodi",
    " Lucas Hernández",
    " Arda Turan",
    " Raúl Jiménez",
    " Mario Mandžukić",
    " Diego Godín",
    " Miranda",
    " Filipe Luís",
    " Marc-André ter Stegen",
    " Álex Balde",
    " Ronald Araújo",
    " Sergiño Dest",
    " Jules Koundé",
    " Clément Lenglet",
    " Sergi Roberto",
    " Frenkie de Jong",
    " Gavi",
    " Pedri",
    " Oriol Romeu",
    " Ansu Fati",
    " Robert Lewandowski",
    " Raphinha",
    " Xavi",
    " Jordi Alba",
    " Busquets",
    " Franck Kessié",
    " Neto",
    " Dani Alves",
    " Samuel Umtiti",
    " Martin Braithwaite",
    " Ousmane Dembélé",
    " Nélson Semedo",
    " Arthur",
    " Ivan Rakitić",
    " Arturo Vidal",
    " Lionel Messi",
    " Quique Setién",
    " Jasper Cillessen",
    " Lucas Digne",
    " André Gomes",
    " Iniesta",
    " Rafinha",
    " Neymar",
    " Paco Alcácer",
    " Luis Enrique",
    " Thomas Vermaelen",
    " Adama Traoré",
    " Éric Abidal",
    " Puyol",
    " Jonathan dos Santos",
    " David Villa",
    " Maxwell",
    " Gabriel Milito",
    " Rafael Márquez",
    " Lilian Thuram",
    " Gianluca Zambrotta",
    " Deco",
    " Ronaldinho",
    " Henrik Larsson",
    " Patrick Kluivert",
    " Emmanuel Petit",
    " Rivaldo",
    " Pelé",
    " Johan Cruyff",
    " Carlos Soler",
    " Érik Lamela",
    " Youssef En-Nesyri",
    " Suso",
    " Marcos Acuña",
    " Lucas Ocampos",
    " Jarrod Bowen",
    " Nayef Aguerd",
    " Saïd Benrahma",
    " Lucas Paquetá",
    " Nabil Fekir",
    " Manuel Neuer",
    " Alphonso Davies",
    " Matthijs de Ligt",
    " Raphaël Guerreiro",
    " Min-jae Kim",
    " Noussair Mazraoui",
    " Benjamin Pavard",
    " Bouna Sarr",
    " Dayot Upamecano",
    " Leon Goretzka",
    " Joshua Kimmich",
    " Jamal Musiala",
    " Choupo-Moting",
    " Kingsley Coman",
    " Thomas Müller",
    " Sven Ulreich",
    " Yann Sommer",
    " Niklas Süle",
    " Corentin Tolisso",
    " Hansi Flick",
    " Javi Martínez",
    " Mats Hummels",
    " Renato Sanches",
    " Franck Ribéry",
    " Juan Bernat",
    " Philipp Lahm",
    " Mario Götze",
    " Dante",
    " Claudio Pizarro",
    " Mario Gómez",
    " Oliver Kahn",
    " Lúcio",
    " Mark van Bommel",
    " Gregor Kobel",
    " Thomas Meunier",
    " Julian Brandt",
    " Marco Reus",
    " Karim Adeyemi",
    " Sébastien Haller",
    " Thorgan Hazard",
    " Donyell Malen",
    " Mahmoud Dahoud",
    " Erik Durm",
    " Matthias Ginter",
    " Shinji Kagawa",
    " Ivan Perišić",
    " Péter Gulácsi",
    " Lukas Klostermann",
    " Dani Olmo",
    " Xavi Simons",
    " Fabio Carvalho",
    " Abdou Diallo",
    " André Silva",
    " Christopher Nkunku",
    " Julian Nagelsmann",
    " Ralf Rangnick",
    " Kevin Trapp",
    " Robin Koch",
    " Omar Marmoush",
    " Gerd Müller",
    " Franz Beckenbauer",
    " Lothar Matthäus",
    " Rudi Völler",
    " Miroslav Klose",
    " Gianluigi Donnarumma",
    " Sergio Rico",
    " Presnel Kimpembe",
    " Layvin Kurzawa",
    " Marquinhos",
    " Nuno Mendes",
    " Milan Škriniar",
    " Danilo Pereira",
    " Julian Draxler",
    " Fabián Ruiz",
    " Marco Verratti",
    " Vitinha",
    " Gonçalo Ramos",
    " Kylian Mbappé",
    " Christophe Galtier",
    " Alessandro Florenzi",
    " Thilo Kehrer",
    " Idrissa Gueye",
    " Abdoulaye Kamara",
    " Xavi Simons",
    " Mauro Icardi",
    " Moise Kean",
    " Pablo Sarabia",
    " Gianluigi Buffon",
    " Leandro Paredes",
    " Moussa Diaby",
    " Hatem Ben Arfa",
    " Adrien Rabiot",
    " Gonçalo Guedes",
    " Unai Emery",
    " Blaise Matuidi",
    " Ezequiel Lavezzi ",
    " Mamadou Sakho",
    " Mohammed Salisu",
    " Kevin Volland",
    " Minamino",
    " Breel Embolo",
    " Wissam Ben Yedder",
    " Denis Zakaria",
    " Benoît Badiashile",
    " Djibril Sidibé",
    " Gelson Martins",
    " Kamil Glik",
    " João Moutinho",
    " Tiemoué Bakayoko",
    " Claudio Ranieri",
    " Anthony Lopes",
    " Houssem Aouar",
    " Moussa Dembélé",
    " Steve Mandanda",
    " Mattéo Guendouzi",
    " Arkadiusz Milik",
    " Cengiz Ünder",
    " Diogo Costa",
    " Otávio",
    " Fábio Vieira",
    " vincent Aboubakar",
    " José Sá",
    " Rúben Neves",
    " Yacine Brahimi",
    " Moussa Marega",
    " Alex Sandro",
    " Hulk",
    " João Mário",
    " Rafa Silva",
    " Júlio César",
    " Anderson Talisca",
    " Rodrigo",
    " Islam Slimani",
    " Eusébio",
    " Mike Maignan",
    " Davide Calabria",
    " Simon Kjær",
    " Malick Thiaw",
    " Ismaël Bennacer",
    " Ruben Loftus-Cheek",
    " Luka Romero",
    " Samuel Chukwueze",
    " Rafael Leão",
    " Stefano Pioli",
    " Ante Rebić",
    " Alexis Saelemaekers",
    " Alessio Romagnoli",
    " Hakan Çalhanoğlu",
    " Daniel Maldini",
    " Samu Castillejo",
    " Ricardo Rodríguez",
    " Manuel Locatelli",
    " Adil Rami",
    " Stephan El Shaarawy",
    " Massimiliano Allegri",
    " Alessandro Nesta",
    " Gennaro Gattuso",
    " Andrea Pirlo",
    " Filippo Inzaghi",
    " Dida",
    " Paolo Maldini",
    " Cafú",
    " Rui Costa",
    " George Weah",
    " Marcel Desailly",
    " Roberto Baggio",
    " Franco Baresi",
    " Ruud Gullit",
    " Marco van Basten",
    " Frank Rijkaard",
    " Stefan de Vrij",
    " Francesco Acerbi ",
    " Federico Dimarco",
    " Nicolò Barella",
    " Denzel Dumfries",
    " Joaquín Correa",
    " Lautaro Martínez",
    " Marcus Thuram",
    " Samir Handanovic",
    " Alessandro Bastoni",
    " Aleksandar Kolarov",
    " Marcelo Brozovic",
    " Robin Gosens",
    " Moisés Caicedo",
    " Victor Moses",
    " Kwadwo Asamoah",
    " Cristiano Biraghi",
    " Radja Nainggolan",
    " Antonio Candreva",
    " Iván Córdoba",
    " Marco Materazzi",
    " Diego Milito",
    " Francesco Toldo",
    " Adriano",
    " Hernán Crespo",
    " Leonardo Bonucci",
    " Javier Zanetti",
    " Gianluca Mancini",
    " Leonardo Spinazzola",
    " Lorenzo Pellegrini",
    " Paulo Dybala",
    " Nicolò Zaniolo",
    " Davide Zappacosta",
    " Justin Kluivert",
    " Patrick Kluivert",
    " Kostas Manolas",
    " Daniele De Rossi",
    " Diego Perotti",
    " Kevin Strootman",
    " Patrik Schick",
    " Miralem Pjanić",
    " Francesco Totti",
    " Luciano Spalletti",
    " Philippe Mexès",
    " Luca Toni",
    " Fabio Capello",
    " Mattia Perin",
    " Wojciech Szczęsny",
    " Daniele Rugani",
    " Weston McKennie",
    " Federico Chiesa",
    " Dušan Vlahović",
    " Timothy Weah",
    " Giorgio Chiellini",
    " Federico Bernardeschi",
    " Gianluigi Buffon",
    " Rodrigo Bentancur",
    " Medhi Benatia",
    " Stephan Lichtsteiner",
    " Claudio Marchisio",
    " Douglas Costa",
    " Andrea Barzagli",
    " Simone Zaza",
    " Alessandro Del Piero",
    " David Trezeguet",
    " Pavel Nedvěd",
    " Bremer",
    " Andrea Belotti",
    " Luis Alberto",
    " Ciro Immobile",
    " Sergej Milinković-Savić",
    " Antonio Di Natale",
    " Alex Meret",
    " Mário Rui",
    " Frank Anguissa",
    " Piotr Zielinski",
    " Khvicha Kvaratskhelia",
    " Hirving Lozano",
    " Victor Osimhen",
    " Giovanni Simeone",
    " Lorenzo Insigne",
    " Faouzi Ghoulam",
    " Dries Mertens",
    " Marek Hamsik",
    " Carlos Vinícius",
    " Duván Zapata",
  ];
  Random random = Random();
  int round = 1;
  late int indexx = random.nextInt(names.length);
  void changePhoto() {
    indexx = random.nextInt(names.length);
    notifyListeners();
  }

  void numberOfRound() {
    round++;
    notifyListeners();
  }
}